# Generated by Django 5.1.4 on 2025-07-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="AsadMaxmud", max_length=100)),
                ("logo", models.ImageField(upload_to="logos/")),
            ],
        ),
    ]
