# Generated by Django 5.1.4 on 2025-07-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_name",
        ),
    ]
