# Generated by Django 5.1.4 on 2025-07-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logo", "0002_remove_sitesettings_site_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Sayt logosi",
                "verbose_name_plural": "Sayt logosi",
            },
        ),
    ]
