# Generated by Django 5.1.4 on 2025-07-09 06:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logo", "0003_alter_sitesettings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="logo"
            ),
        ),
    ]
