# Generated by Django 5.1.4 on 2025-07-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logo", "0004_alter_sitesettings_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, verbose_name="Footer matni"),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamasi",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
    ]
