"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import dj_database_url

from environs import Env
env = Env()
Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os

from .unfold_settings import UNFOLD
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-eh!78m07+#_4nhy$a(v67kxh_e%%^9opf)3*w7^&##8fki6e+&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



ALLOWED_HOSTS = [
    '*'
]

CORS_ALLOWED_ORIGINS = [
    'https://asadmaxmud.up.railway.app'
]

CORS_ALLOW_ALL_ORIGINS = True



CSRF_TRUSTED_ORIGINS = ['https://asadmaxmud.up.railway.app']

# Application definition

INSTALLED_APPS = [
    "unfold",
    'corsheaders',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # install apps
    'rest_framework',
    'django_core',
    'payme',
    'cloudinary',
    'cloudinary_storage',

    # other apps
    'users',
    'api',
    'basket',
    'product',
    'order',
    'bot',
    'payment',
    'services',
    'logo.apps.LogoConfig',
    'social',
    'subscriptions',
]


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env("CLOUDINARY_CLOUD_NAME"),
    'API_KEY': env("CLOUDINARY_API_KEY"),
    'API_SECRET': env("CLOUDINARY_API_SECRET"),
}

PAYME_ID=env('PAYME_ID')
PAYME_KEY='wy2vK&zN7Gq9@#KtAKv9Pr9nRPqhTZtNE&Nx'
PAYME_ACCOUNT_MODEL="order.models.order.PaymentSession"

PAYME_ACCOUNT_FIELD = "id"  
PAYME_AMOUNT_FIELD = "total_amount"
PAYME_ONE_TIME_PAYMENT = True  

CLICK_SERVICE_ID = "76984"
CLICK_MERCHANT_ID = "41452"
CLICK_SECRET_KEY = "r3MfWkyuMPurM"
CLICK_ACCOUNT_MODEL = "order.models.order.PaymentSession"
CLICK_AMOUNT_FIELD = "total_amount" 

BOT_TOKEN = env('BOT_TOKEN')

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Qo‘shish
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ASADMAXMUD_SHOP/settings.py

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'users.authentication.TelegramAuthentication',  
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',  # Foy
#     ],
# }


WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        "postgresql://posrgres_db_l9jl_user:8bIpoLsGqo83MKfmbUtKkjm8D8WSnUKc@dpg-d1n3onndiees73emsgh0-a.oregon-postgres.render.com/posrgres_db_l9jl", 
        conn_max_age=600, 
        ssl_require=True
    )
}

# POSTGRESQL = True
# if POSTGRESQL:
#     DATABASES['default'] = dj_database_url.parse(env('DATABASE_URL'))

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/' 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), 
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
MEDIA_URL = '/media/'  
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")