# Generated by Django 5.1.4 on 2025-07-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.CharField(max_length=64)),
                (
                    "username",
                    models.CharField(
                        help_text="Foydalanuvchilar ushbu username orqali admin bilan bog‘lanadi",
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
