# Generated by Django 5.1.4 on 2025-07-09 06:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="icon"
                    ),
                ),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name": "Ijtimoiy tarmoq",
                "verbose_name_plural": "Ijtimoiy tarmoqlar",
            },
        ),
    ]
